
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/TuyaInc/TuyaPublicSpecs.git'

platform :ios, '9.0'

target 'TuyaSmartiOSBizBundleDemo_OC' do
  
  # bizBundle
  pod 'TuyaSmartCameraPanelBizBundle'
  pod 'TuyaSmartCameraRNPanelBizBundle'
  pod 'TuyaSmartPanelBizBundle'
  pod 'TuyaSmartActivatorBizBundle'
  pod 'TuyaSmartMallBizBundle'
  pod 'TuyaSmartSceneBizBundle'
  pod 'TuyaSmartMessageBizBundle'
  pod 'TuyaSmartHelpCenterBizBundle'
  # Demo
  pod 'TuyaSmartDemo', :subspecs => [
    'Login',
    'DeviceList',
    'SmartScene',
    'UserInfo'
  ]
end
